[versions]

junit = "6.0.2"
kotest = "6.1.0"

# This build uses DevPublish to test itself. Versions are timestamped snapshots, which Central deletes after 90 days.
# Find new versions in https://central.sonatype.com/repository/maven-snapshots/dev/adamko/gradle/<module>/<version>/maven-metadata.xml
# TODO replace with 1.2.0 when the next version is released
devPublishBootstrap = "1.2.0-20261008.110542-20"

gradlePlugin-pluginPublishPlugin = "2.2.1"
gradlePlugin-nmcp = "1.6.2"

[libraries]

## region Test Libraries
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-runnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
## endregion

## region Gradle Plugins
gradlePlugin-pluginPublishPlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePlugin-pluginPublishPlugin" }
gradlePlugin-nmcp = { module = "com.gradleup.nmcp:nmcp", version.ref = "gradlePlugin-nmcp" }
## endregion

## region DevPublish bootstrap
devPublishBootstrap-plugin = { module = "dev.adamko.gradle:dev-publish-plugin", version.ref = "devPublishBootstrap" }
devPublishBootstrap-common = { module = "dev.adamko.gradle:dev-publish-common", version.ref = "devPublishBootstrap" }
devPublishBootstrap-utils = { module = "dev.adamko.gradle:dev-publish-utils", version.ref = "devPublishBootstrap" }
## endregion
