@file:Suppress("UnstableApiUsage")

import buildsrc.utils.ProjectTestTempDirArgument.Companion.ProjectTestTempDirArgument
import buildsrc.utils.skipTestFixturesPublications
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText
import org.gradle.plugin.compatibility.compatibility
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.abi.ExperimentalAbiValidation

plugins {
  buildsrc.conventions.`kotlin-gradle-plugin`
  `java-test-fixtures`
  id("dev.adamko.dev-publish")
}

dependencies {
  implementation(projects.modules.devPublishCommon)

  // the tests, and the generated test projects, resolve these from the dev Maven repo
  devPublication(projects.modules.devPublishCommon)
  devPublication(projects.modules.devPublishUtils)

  testFixturesImplementation(projects.modules.devPublishUtils)
  testFixturesApi(gradleTestKit())
  testFixturesApi(platform(libs.kotest.bom))
  testFixturesApi(libs.kotest.runnerJUnit5)
  testFixturesApi(libs.kotest.assertionsCore)
}

kotlin {
  compilerOptions {
    optIn.addAll(
      "kotlin.io.path.ExperimentalPathApi",
      "dev.adamko.gradle.dev_publish.internal.DevPublishInternalApi",
    )
  }
  @OptIn(ExperimentalAbiValidation::class)
  abiValidation {
    filters {
      exclude {
        annotatedWith.add("dev.adamko.gradle.dev_publish.internal.DevPublishInternalApi")
      }
    }
  }
}

gradlePlugin {
  website = "https://github.com/adamko-dev/dev-publish-plugin"
  vcsUrl = "https://github.com/adamko-dev/dev-publish-plugin.git"

  plugins.register("DevPublish") {
    id = "dev.adamko.dev-publish"
    displayName = "DevPublish"
    description = "Publish Gradle Projects to a project-local repository, for functional testing"
    implementationClass = "dev.adamko.gradle.dev_publish.DevPublishPlugin"
    tags.addAll(
      "maven",
      "publishing",
      "maven-publish",
      "test",
      "verify",
      "check",
      "functional-test",
      "integration-test",
      "publication",
    )
    compatibility {
      features {
        isolatedProjects = true
        configurationCache = true
      }
    }
  }
}

val projectTestTempDir: Provider<Directory> = layout.buildDirectory.dir("project-tests")

skipTestFixturesPublications()

val rootProjectDir = isolated.rootProject.projectDirectory

/** The `examples/` projects. */
val exampleFiles: FileCollection =
  rootProjectDir.dir("examples").asFileTree


tasks.withType<Test>().configureEach {
  val projectTestTemp = projectTestTempDir
  jvmArgumentProviders.add(
    objects.ProjectTestTempDirArgument {
      projectTestTempDir = projectTestTemp
    }
  )
}

testing.suites {
  named<JvmTestSuite>("test") {
    dependencies {
      implementation(projects.modules.devPublishUtils)
      implementation(devPublish.dependency())
    }

    targets.configureEach {
      testTask.configure {
        // ExamplesTest builds these, so they are inputs - not that Gradle could know.
        inputs.files(exampleFiles)
          .withPropertyName("exampleFiles")
          .withPathSensitivity(PathSensitivity.RELATIVE)
      }
    }
  }

  // The docs tests only read files, so they are fast, and are kept away from the slow TestKit
  // tests - but they are also the only tests whose inputs are the docs themselves.
  register<JvmTestSuite>("testDocs") {
    dependencies {
      implementation(testFixtures(project()))
      implementation(platform(libs.kotest.bom))
      implementation(libs.kotest.runnerJUnit5)
      implementation(libs.kotest.assertionsCore)
    }

    targets.named("testDocs") {
      testTask.configure {
        description = "Checks the docs."
      }
    }

    targets.configureEach {
      testTask.configure {
        inputs.files(isolated.rootProject.projectDirectory.asFileTree.matching {
          include("**/*.md")
          exclude("**/build/**", "**/.gradle/**", "**/.git/**")
        })
          .withPropertyName("docsFiles")
          .withPathSensitivity(PathSensitivity.RELATIVE)

        // ReadmeSnippetsTest compares the README's snippets against examples.
        inputs.files(exampleFiles)
          .withPropertyName("exampleFiles")
          .withPathSensitivity(PathSensitivity.RELATIVE)
      }
    }
  }
}

tasks.check {
  dependsOn(testing.suites.named("testDocs"))
}

val generateDevPublishVersionKt by tasks.registering {
  val outputDir = temporaryDir.toPath()
  outputs.dir(outputDir)

  val projectVersion = provider { project.version.toString() }
  inputs.property("version", projectVersion)
  doLast {
    outputDir
      .resolve("dev/adamko/gradle/dev_publish/internal")
      .createDirectories()
      .resolve("DevPublishVersion.kt")
      .writeText(
        """
        |// Do not edit: generated by $path
        |package dev.adamko.gradle.dev_publish.internal
        |
        |/** The current version of the DevPublish plugin. */
        |internal const val DevPublishVersion = "${projectVersion.get()}"
        |""".trimMargin()
      )
  }
}

kotlin.sourceSets.main {
  @OptIn(ExperimentalKotlinGradlePluginApi::class)
  generatedKotlin.srcDir(generateDevPublishVersionKt)
}
